### ISSUE TITLE
Fix gossipsub tests to use `LRUCache` api

### ISSUE THREAD

**Issue by pawanjay176** [sigp/rust-libp2p#8]
## Description

Fix `test_handle_ihave_subscribed_and_msg_cached` in gossipsub tests to use `put` method of `LRUCache` over `add` method of previously used `CuckooFilter`.

Note: Test doesn't fail if `msg_id` doesn't exist in the `received` cache.

**Comment by AgeManning** [comment]
This already seems to be done?
https://github.com/sigp/rust-libp2p/blob/gossipsub/protocols/gossipsub/src/behaviour/tests.rs#L592

**Comment by pawanjay176** [comment]
Yup, sorry. I was testing on `interop`.
